name = "rincondelhype-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[images]
binding = "IMAGES"

[vars]
ALLOWED_ORIGINS = "http://localhost:4321,https://rincon-del-hype.pages.dev,https://rincondelhype.com,https://www.rincondelhype.com"
